### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by therealnv6** [TehNeon/StaffDisplay#4]
Hey. I was trying to use this plugin, however it broke with the interaction. 
![image](https://user-images.githubusercontent.com/96917554/192651565-abb11f07-3349-417b-9722-f2fa121fb7a2.png)

**Comment by GrowlyX** [comment]
Yes, I'm having a similar issue. My players IRL are waiting for this to be fixed so we can have Staff Display working. 

Thank you,
GrowlyX.

**Comment by therealnv6** [comment]
Yes, I'm having a similar issue too!

**Comment by GrowlyX** [comment]
> Yes, I'm having a similar issue too!

Me too! Any ETA on this being fixed?

**Comment by therealnv6** [comment]
> > Yes, I'm having a similar issue too!
> 
> Me too! Any ETA on this being fixed?

By the way, I also realized a TYPO. It says tehneon instead of theos!

**Comment by GrowlyX** [comment]
> > > Yes, I'm having a similar issue too!
> > 
> > 
> > Me too! Any ETA on this being fixed?
> 
> By the way, I also realized a TYPO. It says tehneon instead of theos!

I also found another error. It says `staffdisplay` instead of staff display!

**Comment by ohemilyy** [comment]
I think this issue can be fix if you check your main class for errors regarding the jfrog artificatory that tends to throw out protocol issues with java exception null handlers @therealnv6
